# Generated by Django 4.0 on 2022-01-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=64)),
                ('customeremail', models.CharField(max_length=50)),
                ('customerphonenumber', models.CharField(max_length=12)),
                ('customerdevice', models.CharField(max_length=50)),
                ('ticketID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketID', models.IntegerField()),
                ('ticketnumber', models.CharField(max_length=50)),
                ('ticketfault', models.CharField(max_length=500)),
                ('ticketdate', models.DateField(auto_now=True)),
                ('tickettime', models.TimeField(auto_now=True)),
                ('ticketstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
