# Generated by Django 4.0 on 2022-01-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0002_alter_customer_customeremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerdevice',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customeremail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customername',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerphonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketfault',
            new_name='fault',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketnumber',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketstatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='tickettime',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ticketID',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticketID',
        ),
    ]
