# Generated by Django 4.0 on 2022-01-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0004_ticket_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
