# Generated by Django 4.0 on 2022-01-13 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0005_fault_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.fault'),
        ),
    ]
