# Generated by Django 4.0 on 2022-01-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0010_remove_ticket_fault_delete_fault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
