# Generated by Django 4.0 on 2022-01-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
