# Generated by Django 4.0 on 2022-01-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0013_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fault',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eStore.fault'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eStore.status'),
        ),
    ]
