# Generated by Django 4.0 on 2022-01-13 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0014_alter_fault_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.fault'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.status'),
        ),
    ]
