# Generated by Django 4.0 on 2022-01-17 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0015_alter_fault_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device',
        ),
        migrations.AddField(
            model_name='ticket',
            name='device',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(),
        ),
    ]
