# Generated by Django 4.0 on 2022-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0017_transaction_ticket_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
