# Generated by Django 4.0 on 2022-01-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0018_remove_transaction_amount_ticket_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number',
        ),
    ]
